<div class="container">
	<div class="row py-5">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header text-center text-white" style="background: #f15060">
					Terms And Conditions
				</div>
				<div class="card-body text-justify">
					<p>This website is owned and operated by jewellery website.com" having its registered office at No. 3, Sipcot Industrial Complex, Hosur-635126, Krishnagiri District, Tamil Nadu and its corporate office at No.132/133 Divyashree Technopolis, Off HAL Airport Road, Yamalur Post, Yamalur, Bangalore- 560037, Karnataka, India.</p>
					<p>In using the services provided by our website jewellerywebsite.com you are deemed to have accepted the terms and conditions listed below or as may be revised from time to time, which is, for an indefinite period and you understand and agree that you are bound by such terms and conditions till the time you access this website.</p>
					<p>ABC Company reserves the right to change these terms and conditions from time to time without any obligation to inform you and it is your responsibility to look through them as often as possible. All rights including copyright, in this website, are owned by ABC Company Limited. Any use of this website or its contents, including copying or storing it in whole or part without the permission of ABC Company Limited is prohibited.</p>
					<p>If you have any queries about these terms and conditions or any complaints or suggestions regarding our website, please feel free to write to customercare@jewellerywebsite.com or call us on 1800-266-0123 (Timings: 10.00 A.M to 7.00 P.M Indian Standard Time).</p>
					<p>If you are below 18 years of age, you are prohibited to use/purchase/contract from or with this website. Persons who are incompetent to contract within the meaning of the Indian Contract Act, 1872 are not eligible to use this website.</p>
					<p>Those who choose to access this website from outside India are responsible for compliance with local laws and if to the extent local laws are applicable. In case if any Indian states prohibit direct sale of merchandise from other states and require special documentation to effect such a sale without dual taxation, if we receive an order from such states or to be delivered to such states under such circumstances we retain the right to accept or reject the order.</p>
					<p>All products and the information displayed on www.jewelleywebsite.com constitute an invitation to offer. Your order for purchase constitutes your offer which shall be subject to the terms and conditions as listed herein. We reserve the right to accept or reject your offer in part or in full. Our acceptance of your order will take place upon the dispatch of the product(s) ordered. Dispatch of product(s) ordered, may or may not happen at the same time. In such a scenario, that portion of the order which has been dispatched will be deemed to have been accepted by us and the balance would continue to be an offer to us and we reserve the right to either accept or reject the balance offer.</p>
					<p>No act or comission of Titan prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer. If you have provided us with your email address, we will notify you by email as soon as possible to confirm receipt of your order and confirm dispatch and therefore, acceptance of the order thereafter.</p>
					<p>We have made every effort to display the colors and sizes of our products that appear on our website as accurately as possible. However, as the actual colors you see will depend on your monitor. We cannot guarantee that your monitor's display of any color will accurately reflect the color of the product on delivery. Packaging of the product may vary from that displayed on the website.</p>
					<p>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this website (collectively content are intended solely for personal and non-commercial use. You may download or copy the contents and other materials displayed on the website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You will not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the contents of the website or any related software. All software used on this website is the property of Titan or its suppliers and they are protected by Indian and international copyright laws.</p>
				</div>
			</div>
		</div>
	</div>
</div>